# Generated by Django 3.2.9 on 2021-12-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_norman_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
